import acm.program.*;
import acm.graphics.*;
import acm.gui.*;
import acm.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *  Respond to Action Events in an ACM Graphics program.
 *
 *  @author Stephen Gilbert
 *  @version Mar 11, 2009 9:06:04 AM
 */
public class ButtonActions extends GraphicsProgram
{
    private GOval theDot;
    private JButton goBtn;
    private JButton colorBtn;
    private DoubleField radiusTf;
    private GPoint center;
    /**
     * Initialize the components.
     */
    public void init()
    {
        // Initialize the center of the app
        // Leave some space for tool bar at bottom
        center = new GPoint(getWidth() / 2, getHeight() / 2 - 20);
        
        // Create the components
        goBtn = new JButton("Change Circle Radius");
        colorBtn = new JButton("Change the Color");
        radiusTf = new DoubleField();
        theDot = new GOval(100, 100);

        // Set mnemonics & tooltips for JButtons, color the oval
        goBtn.setMnemonic('R');
        colorBtn.setMnemonic('C');
        goBtn.setToolTipText("Click to change the circle radius");
        theDot.setFilled(true);
        theDot.setFillColor(Color.YELLOW);

        // Add everything to the app
        add(new JLabel("Enter new radius: "), SOUTH);
        add(radiusTf, SOUTH);
        add(goBtn, SOUTH);
        add(colorBtn, SOUTH);
        double radius = 50;
        add(theDot, center.getX() - radius, center.getY() - radius);

        // Respond to ActionEvents generated by the button
        addActionListeners();
    }
    
    /**
     * Respond to button clicks in the application.
     */
    public void actionPerformed(ActionEvent e)
    {
        if (e.getActionCommand().equals("Change Circle Radius"))
        {
            int color = (int)(Math.abs(Math.random() * Integer.MAX_VALUE));
            theDot.setFillColor(new Color(color));
        }
        else if (e.getActionCommand().equals("Change the Color"))
        {
            double newRadius = radiusTf.getValue();
            
            theDot.setLocation(center.getX() - newRadius, 
                               center.getY() - newRadius);
            theDot.setSize(newRadius * 2, newRadius * 2);
        }
        
        
        // Done? Select the text field again
        radiusTf.selectAll();
        radiusTf.requestFocus();
    }
    
    /**
     * The standard Java entry point. DON'T MODIFY.
     * @param args the command-line arguments.
     */
    public static void main(String[] args)
    {
        new ButtonActions().start(args);
    }
}
