# Steve Gilbert's Modifications for OCC
# Global initialisation file for SciTE
# For Windows, place in same directory as Sc1.EXE

# Globals

# Window sizes and visibility
# Modify these to change initial size and position
position.left=0
position.top=0
position.width=640
position.height=480

# Modify these to change layout of screen
buffers=20
split.vertical=0
tabbar.visible=1
tabbar.multiline=1
toolbar.visible=1
statusbar.visible=1

# Sizes and visibility in edit pane
# Set line.numbers to 4 if you want to see them
line.margin.visible=1
line.margin.width=3+
buffered.draw=1
use.palette=0

# Element styles
caret.period=500
view.whitespace=0
view.indentation.whitespace=1
view.indentation.guides=1
highlight.indentation.guides=1
edge.column=200
edge.mode=0
edge.colour=#C0DCC0
braces.check=1
braces.sloppy=1

selection.back=#DADADA
use.monospaced=1

# Checking
are.you.sure=1
load.on.activate=1
default.file.ext=.java
title.full.path=1
strip.trailing.spaces=1
ensure.final.line.end=1
ensure.consistent.line.ends=1

# Indentation
tabsize=4
indent.size=4
use.tabs=0
indent.automatic=1
indent.opening=0
indent.closing=0
tab.indents=1
backspace.unindents=1
output.wrap=1

# Folding
# enable folding, and show lines below when collapsed.
fold=1
fold.compact=1
fold.flags=16
fold.symbols=1

# Behaviour
clear.before.execute=0
caret.policy.xslop=1
caret.policy.width=20
caret.policy.xstrict=0
caret.policy.xeven=0
caret.policy.xjumps=0
caret.policy.yslop=1
caret.policy.lines=1
caret.policy.ystrict=1
caret.policy.yeven=1
caret.policy.yjumps=0

# Status Bar
statusbar.number=4
statusbar.text.1=\
li=$(LineNumber) co=$(ColumnNumber) $(OverType) ($(EOLMode)) $(FileAttr)
statusbar.text.2=\
$(BufferLength) chars in $(NbOfLines) lines. Sel: $(SelLength) chars.
statusbar.text.3=\
Now is: Date=$(CurrentDate) Time=$(CurrentTime)
statusbar.text.4=\
$(FileNameExt) : $(FileDate) ó $(FileTime) | $(FileAttr)

command.scite.help="file://$(SciteDefaultHome)\SciTEDoc.html"
command.scite.help.subsystem=2

code.page=0

# Export
export.html.wysiwyg=1
export.html.styleused=1

# Define values for use in the imported properties files
chars.alpha=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
chars.numeric=0123456789
chars.accented=äöåúüˇ¿‡¡·¬‚√„ƒ‰≈Â∆Ê«Á»Ë…È ÍÀÎÃÏÕÌŒÓœÔ–—Ò“Ú”Û‘Ù’ı÷ÿ¯Ÿ˘⁄˙€˚‹¸›˝ﬁ˛ﬂˆ
# This is a better set for Russian:
#chars.accented=¿‡¡·¬‚√„ƒ‰≈Â®∏∆Ê«Á»Ë…È ÍÀÎÃÏÕÌŒÓœÔ–—Ò“Ú”Û‘Ù’ı÷ˆ◊˜ÿ¯Ÿ˘⁄˙€˚‹¸›˝ﬁ˛ﬂˇ

# The open.filter setting is only used on Windows where the file selector has a menu of filters to apply
# to the types of files seen when opening.
# There is a limit (possibly 256 characters) to the length of a filter,
# so not all source extensions can be in this setting.
source.files=*.asm;*.c;*.cc;*.cpp;*.cxx;*.cs;*.h;*.hh;*.hxx;*.hpp;\
*.idl;*.odl;*.rc;*.rc2;*.dlg;*.def;\
*.vb;*.vbs;*.bas;*.frm;*.cls;*.ctl;\
*.java;*.js;*.jsp;*.py;*.pl;*.rb;*.cgi;*.lua;*.conf;\
make*;*.mak;\
*.properties;*.html;*.xml;*.iface;*.bat;*.e

open.filter=\
All Source|$(source.files)|\
All Files (*.*)|*.*|\
$(filter.ada)\
$(filter.conf)\
$(filter.asm)\
$(filter.ave)\
$(filter.baan)\
$(filter.cpp)\
$(filter.css)\
$(filter.eiffel)\
$(filter.fortran)\
$(filter.idl)\
$(filter.java)\
$(filter.js)\
$(filter.jsp)\
$(filter.latex)\
$(filter.lout)\
$(filter.lua)\
$(filter.matlab)\
$(filter.nncrontab)\
$(filter.pascal)\
$(filter.perl)\
$(filter.php)\
$(filter.pov)\
$(filter.properties)\
$(filter.python)\
$(filter.ruby)\
$(filter.sql)\
$(filter.tcl)\
$(filter.text)\
$(filter.vb)\
$(filter.web)

# Give symbolic names to the set of fonts used in the standard styles.
#font.base=font:Verdana,size:10
#font.small=font:Verdana,size:8
#font.comment=font:Comic Sans MS,size:9
#font.code.comment.box=$(font.comment)
#font.code.comment.line=$(font.comment)
#font.code.comment.doc=$(font.comment)
#font.text=font:Times New Roman,size:11
#font.text.comment=font:Verdana,size:9
#font.embedded.base=font:Verdana,size:9
#font.embedded.comment=font:Comic Sans MS,size:8
#font.monospace=font:Andale Mono,size:10
#font.vbs=font:Lucida Sans Unicode,size:10
#font.js=$(font.comment)

font.base=font:Lucida Console,size:10
font.small=font:Lucida Console,size:8
font.comment=font:Lucida Sans,size:10
font.code.comment.box=$(font.comment)
font.code.comment.line=$(font.comment)
font.code.comment.doc=$(font.comment)
font.text=font:Lucida Console,size:10
font.text.comment=font:Lucida Console,size:9
font.embedded.base=font:Lucida Console,size:9
font.embedded.comment=font:Comic Sans MS,size:8
font.monospace=font:Courier New,size:9
#font.monospace=font:Andale Mono,size:8
#font.monospace=font:Lucida Sans Unicode,size:10
font.vbs=font:Lucida Sans Unicode,size:10
font.js=$(font.comment)

# Give symbolic names to the set of colours used in the standard styles.
colour.code.comment.box=fore:#007F00
colour.code.comment.line=fore:#007F00
colour.code.comment.doc=fore:#3F703F
colour.text.comment=fore:#0000FF,back:#D0F0D0
colour.other.comment=fore:#007F00
colour.embedded.comment=back:#E0EEFF
colour.embedded.js=back:#F0F0FF
colour.notused=back:#FF0000

colour.number=fore:#007F7F
colour.keyword=fore:#00007F
colour.string=fore:#7F007F
colour.char=fore:#7F007F
colour.operator=fore:#000000
colour.preproc=fore:#7F7F00
colour.error=fore:#FFFF00,back:#FF0000

# Global default styles for all languages
# Default
style.*.32=$(font.base)
# Line number
style.*.33=back:#C0C0C0,$(font.base)
# Brace highlight
style.*.34=fore:#0000FF,bold
# Brace incomplete highlight
style.*.35=fore:#FF0000,bold
# Control characters
style.*.36=
# Indentation guides
style.*.37=fore:#C0C0C0,back:#FFFFFF

# Printing - only works on Windows
print.magnification=-1
# Setup: left, right, top, bottom margins, in local units:
# hundredths of millimeters or thousandths of inches
print.margins=1000,750,750,750
# Header/footer:
# && = &; &p = current page
# &f = file name; &F = full path
# &d = file date; &D = current date
# &t = file time; &T = full time
print.header.format=$(FileNameExt) ó Printed on $(CurrentDate), $(CurrentTime) ó Page $(CurrentPage)
print.footer.format=$(FilePath) ó File date: $(FileDate) ó File time: $(FileTime)
# Header/footer style
print.header.style=font:Courier New,size:8
print.footer.style=font:Courier New,size:8

# Define the Lexer menu,
# Each item contains three parts: menu string | file extension | key
# The only keys allowed currently are based on F-keys and alphabetic keys and look like
# [Ctrl+][Shift+][Fn|a] such as F12 or Ctrl+Shift+D.
# A '&' may be placed before a letter to be used as an accelerator. This does not work on GTK+.
menu.language=\
Text|txt|Shift+F11|\
&Batch|bat||\
Bullant|ant||\
&C / C++|c||\
C&#|cs||\
CSS|css||\
&Fortran|f90||\
H&ypertext|html|F12|\
&Java|java||\
Java&Script|js||\
Pascal|pas||\
Pe&rl|pl||\
P&HP|php||\
P&LSQL|spec||\
&Properties|properties||\
Pytho&n|py||\
Reso&urce|rc||\
Shell|sh||\
S&QL|sql||\
&TCL|tcl||\
&VB|vb||\
VBScr&ipt|vbs||\
&XML|xml|Shift+F12|

# User defined key commands
user.shortcuts=\
Ctrl+PageUp|IDM_PREVFILE|\
Ctrl+PageDown|IDM_NEXTFILE|
#KeypadPlus|IDM_EXPAND|\
#KeypadMinus|IDM_BLOCK_COMMENT|

# Import all the language specific properties files
import ada
import asm
import ave
import baan
import bullant
import conf
import cpp
import css
import eiffel
import escript
import fortran
import html
import latex
import lisp
import lout
import lua
import matlab
import nncrontab
import others
import pascal
import perl
import pov
import python
import ruby
import sql
import tcl
import vb

# Specific changes for my environment
# Add compile (not just build) to cs menu
command.compile.*.cs=csc $(FileNameExt)
command.go.*.cs=$(FileName)
command.go.subsystem.*.cs=2

command.name.1.*.java=Java 1.1 Compile (ACM)
command.1.*.java=javac -cp .;acm.jar -source 1.2 -target 1.1 $(FileNameExt)
command.name.2.*.java=Run ACM Program
command.2.*.java=java -cp .;acm.jar $(FileName) code=$(FileName).class

command.name.3.*.java=Java 5 (only) Compile
command.3.*.java=javac -classpath .;acm.jar -source 1.5 -target 1.5 $(FileNameExt)

# g++ command
command.compile.*.cpp=g++ -ansi -pedantic -Wall -g3 -o $(FileName).exe $(FileNameExt)

# Compile using VC++
command.name.1.*.cpp=VC++ 2002 Compile
command.1.*.cpp=cl /nologo /GX /GR /Zi /Za /Zc:forScope /D_DEBUG /MLd /Fe$(FileName) $(FileNameExt)
command.is.filter.0.*.java=1

# This adds the Appletviewer command to the menu and launches it when
# the current file in the editor is an html file.
command.name.0.*.html=Applet Viewer
command.0.*.html=appletviewer $(FileNameExt)
command.subsystem.0.*.html=1

# Adds indenting for Java, C, and CPP
command.name.0.*.java=Indent
command.0.*.java=astyle --style=ansi -s --convert-tabs $(FileNameExt)
command.is.filter.0.*.java=1

command.name.0.*.cpp=Indent
command.0.*.cpp=astyle --style=ansi  -s --convert-tabs $(FileNameExt)
command.is.filter.0.*.cpp=1

command.name.0.*.c=Indent
command.0.*.c=astyle --style=ansi $(FileNameExt)
command.is.filter.0.*.c=1

# Adds jsp to the list of Web styles
file.patterns.html=$(file.patterns.html);*.aspx;*.jsp;
lexer.$(file.patterns.html)=hypertext

# Default
# style.*.32=back:#FFFFE0$(font.base)

# Find in files works on 2K and XP
find.command=findstr /i /n /s $(find.what) $(find.files)

style.hypertext.15=fore:#FF0000
# ASP Javascript
# JS Start - allows eol filled background to not start on same line as SCRIPT tag
style.hypertext.55=fore:#7F7F00
# JS Default
style.hypertext.56=fore:#000000,bold,$(font.js)
# JS Comment
style.hypertext.57=fore:#007F00,$(font.js)
# JS Line Comment
style.hypertext.58=fore:#007F00,$(font.js)
# JS Doc comment
style.hypertext.59=fore:#7F7F7F,bold,$(font.js)
# JS Number
style.hypertext.60=fore:#007F7F,$(font.js)
# JS Word
style.hypertext.61=fore:#000000,$(font.js)
# JS Keyword
style.hypertext.62=fore:#00007F,bold,$(font.js)
# JS Double quoted string
style.hypertext.63=fore:#7F007F,$(font.js)
# JS Single quoted string
style.hypertext.64=fore:#7F007F,$(font.js)
# JS Symbols
style.hypertext.65=fore:#000000,bold,$(font.js)
