# MASTER Schedule for CS 170
#YEAR 2013

#WK 1 1/28 1/31
#IC1A 1/28 1/28 1/29 1/29
L01=Start DrJava and successfully log in|1|
L02=Log into CS 170 Piazza and introduce yourself|1|
L03=Log into CS 170 Checkresults Console|1|

#IC1B 1/29 1/28 1/29 1/29
#1B - Java Computers and Memory, MemoryView, August 28
L04=Exploring Memory Lab|2|

#IC1C 1/30 1/30 1/31 1/31
#1C Read Java Mechanics, turn in first Homework, August 29
Q01=Computer Basics and Java Mechanics|2|
H01=My First Console Program|1|
L05=TicTacToeBoardPrinter|1|
L06=StaircasePrinter|1|

#IC1D 1/31 1/30 1/31 1/31
#1D - Second Homework
H02=My First GUI Program|1|
H03=My First Java Applet|1|
L07=Dash of Nash|2|

# =============== Week 2 =========================
#WK 2 2/4 2/7
#IC2A 2/4 2/4 2/5 2/5
H04=Windows Shell I|1|
H05=Output: PrintMessage|1|
L08=Output: Spikey|1|
L09=ACM Ouput: ACM Basics|1|

#IC2B 2/5 2/4 2/5 2/5
H06=Output: Difference|1|
L10=Output: Huggy Bear|2|

#IC2C 2/6 2/6 2/7 2/7
H07=IPO Basics: Greeter|1|
L11=IPO-Celsius to Fahrenheit|1|
L12=IPO-Feet to Meters|1|

#IC2D 2/7 2/6 2/7 2/7
#2D PQ01

