#TT-EVE Schedule ------------

L01=Start DrJava and successfully log in|1|1/29/2013 9:00 PM
L02=Log into CS 170 Piazza and introduce yourself|1|1/29/2013 9:00 PM
L03=Log into CS 170 Checkresults Console|1|1/29/2013 9:00 PM

#1B - Java Computers and Memory, MemoryView, August 28
L04=Exploring Memory Lab|2|1/29/2013 9:00 PM

#1C Read Java Mechanics, turn in first Homework, August 29
Q01=Computer Basics and Java Mechanics|2|1/31/2013 9:00 PM
H01=My First Console Program|1|1/31/2013 6:10 PM
L05=TicTacToeBoardPrinter|1|1/31/2013 9:00 PM
L06=StaircasePrinter|1|1/31/2013 9:00 PM

#1D - Second Homework
H02=My First GUI Program|1|1/31/2013 6:10 PM
H03=My First Java Applet|1|1/31/2013 6:10 PM
L07=Dash of Nash|2|1/31/2013 9:00 PM

# =============== Week 2 =========================
H04=Windows Shell I|1|2/5/2013 6:10 PM
H05=Output: PrintMessage|1|2/5/2013 6:10 PM
L08=Output: Spikey|1|2/5/2013 9:00 PM
L09=ACM Ouput: ACM Basics|1|2/5/2013 9:00 PM

H06=Output: Difference|1|2/5/2013 6:10 PM
L10=Output: Huggy Bear|2|2/5/2013 9:00 PM

H07=IPO Basics: Greeter|1|2/7/2013 6:10 PM
L11=IPO-Celsius to Fahrenheit|1|2/7/2013 9:00 PM
L12=IPO-Feet to Meters|1|2/7/2013 9:00 PM

#2D PQ01

